name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Lint Python code
        run: |
          pip install pylint
          pylint lambda_function.py

      - name: Deploy Lambda function
        run: |
          aws cloudformation package --template-file lambda_template.yml --s3-bucket YOUR_S3_BUCKET_NAME --output-template-file packaged.yaml
          aws cloudformation deploy --template-file packaged.yaml --stack-name LambdaStack --capabilities CAPABILITY_IAM
